###
http://localhost:3000/events/

###
POST http://localhost:3000/auth/register 
Content-Type: application/json

{
    "name": "Gnanendra G",
    "email": "gnani@gmail.com",
    "password": "123456"
}

###
POST http://localhost:3000/auth/login 
Content-Type: application/json

{
    "email": "gnani@gmail.com",
    "password": "123456" 
}

###
POST http://localhost:3000/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6InZPQVhIN1FWa1FLdXg1V3MiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2N0YWZhb3RvdndqYXp2c2ljbG1zLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI5ODUxZmUyMy1jNjhkLTRhOWYtOTZkZC00M2IwYzliMTFkNzMiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzIyNjkzNzg5LCJpYXQiOjE3MjI2OTAxODksImVtYWlsIjoiZ25hbmlAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6ImduYW5pQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiI5ODUxZmUyMy1jNjhkLTRhOWYtOTZkZC00M2IwYzliMTFkNzMifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTcyMjY5MDE4OX1dLCJzZXNzaW9uX2lkIjoiMDgzNGQzNWUtOWI1ZC00MzhhLTk5ZDQtNWQyOTIyNjU1OWYxIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.KsPG3ZEOT4eUsTCHzHuBEl_-OTZS4t0MKT6VpWRxfaY

{
    "sessionId": "66ae2b00438fd366c09cf5ee"
}

###
GET http://localhost:3000/events/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6InZPQVhIN1FWa1FLdXg1V3MiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2N0YWZhb3RvdndqYXp2c2ljbG1zLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI5ODUxZmUyMy1jNjhkLTRhOWYtOTZkZC00M2IwYzliMTFkNzMiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzIyNjgyNjk5LCJpYXQiOjE3MjI2NzkwOTksImVtYWlsIjoiZ25hbmlAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6ImduYW5pQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiI5ODUxZmUyMy1jNjhkLTRhOWYtOTZkZC00M2IwYzliMTFkNzMifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTcyMjY3OTA5OX1dLCJzZXNzaW9uX2lkIjoiNTZjOTQ2MTEtYTMxYy00OTk3LWIxYTYtYjMyYTgyYzczN2E4IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.65kwaVCQv0OjGZtnU55TESL1mOhzt7navpL90KJOrZo

###
POST http://localhost:3000/events/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6InZPQVhIN1FWa1FLdXg1V3MiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2N0YWZhb3RvdndqYXp2c2ljbG1zLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI5ODUxZmUyMy1jNjhkLTRhOWYtOTZkZC00M2IwYzliMTFkNzMiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzIyNzA1NTM5LCJpYXQiOjE3MjI3MDE5MzksImVtYWlsIjoiZ25hbmlAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6ImduYW5pQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiI5ODUxZmUyMy1jNjhkLTRhOWYtOTZkZC00M2IwYzliMTFkNzMifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTcyMjcwMTkzOX1dLCJzZXNzaW9uX2lkIjoiM2RmNjIxMjktMTJiOC00ZDU2LWIwODgtYWEyZGU5YTdjNzgwIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.hRyfOfJ_i3bwnac7pqRrjy2nFsB9acshfWwvklDp_68
 
 {
    "title": "Product Launch",
    "date": "September 5, 2024",
    "location": "New York, NY",
    "description": "Launching our new AI-powered smart home device with interactive demos and networking opportunities.",
 }

###
PUT http://localhost:3000/events/66addd184301432f2a8bb85b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6InZPQVhIN1FWa1FLdXg1V3MiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2N0YWZhb3RvdndqYXp2c2ljbG1zLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI5ODUxZmUyMy1jNjhkLTRhOWYtOTZkZC00M2IwYzliMTFkNzMiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzIyNjg2NDY0LCJpYXQiOjE3MjI2ODI4NjQsImVtYWlsIjoiZ25hbmlAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6ImduYW5pQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiI5ODUxZmUyMy1jNjhkLTRhOWYtOTZkZC00M2IwYzliMTFkNzMifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTcyMjY4Mjg2NH1dLCJzZXNzaW9uX2lkIjoiYjIzN2M1ZGYtNjNlZi00MjUzLThkNDktZTYzNTYwYmQ2YmRkIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.kPwkgypDlN1eRF7tTh6k00Snz54V5bNXoPAuqco7-jc

 {
    "description": "Annual tech conference featuring the latest innovations in AI, VR, Data Science and blockchain technologies."
 }

###
PUT http://localhost:3000/user/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6InZPQVhIN1FWa1FLdXg1V3MiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2N0YWZhb3RvdndqYXp2c2ljbG1zLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI5ODUxZmUyMy1jNjhkLTRhOWYtOTZkZC00M2IwYzliMTFkNzMiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzIyNjg2NDY0LCJpYXQiOjE3MjI2ODI4NjQsImVtYWlsIjoiZ25hbmlAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6ImduYW5pQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiI5ODUxZmUyMy1jNjhkLTRhOWYtOTZkZC00M2IwYzliMTFkNzMifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTcyMjY4Mjg2NH1dLCJzZXNzaW9uX2lkIjoiYjIzN2M1ZGYtNjNlZi00MjUzLThkNDktZTYzNTYwYmQ2YmRkIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.kPwkgypDlN1eRF7tTh6k00Snz54V5bNXoPAuqco7-jc

{
    "name": "Gnanendra G"
}

###
GET http://localhost:3000/sessions/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6InZPQVhIN1FWa1FLdXg1V3MiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2N0YWZhb3RvdndqYXp2c2ljbG1zLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI0NmI0NTI1MS1iNDdhLTQ4NjUtOWUxNy01ZmM1MmI0Y2VkMmUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzIyNjk1NDEzLCJpYXQiOjE3MjI2OTE4MTMsImVtYWlsIjoiZGVtb0BnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoiZGVtb0BnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInBob25lX3ZlcmlmaWVkIjpmYWxzZSwic3ViIjoiNDZiNDUyNTEtYjQ3YS00ODY1LTllMTctNWZjNTJiNGNlZDJlIn0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3MjI2OTE4MTN9XSwic2Vzc2lvbl9pZCI6IjU4NmFmOWIyLWY1YTYtNDA4ZC1iNDc0LWY2OTY0NGNiOWM3ZiIsImlzX2Fub255bW91cyI6ZmFsc2V9.RKk8RrYyFfzEJpFptRhQToZNzH-iVloG1XqDNdGvj-0

