###
http://localhost:3000/events/

###
POST http://localhost:3000/events/
Content-Type: application/json

 {
      "title": "Tech Conference 2024",
      "date": "August 15, 2024",
      "location": "San Francisco, CA",
      "description": "Annual tech conference featuring the latest innovations in AI, VR, and blockchain technologies."
 }

###
POST http://localhost:3000/auth/register 
Content-Type: application/json
Authorization: 'Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6InZPQVhIN1FWa1FLdXg1V3MiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2N0YWZhb3RvdndqYXp2c2ljbG1zLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIzZDQ2MGQ2NC05ODJkLTQ5Y2EtYTFlNS02MzU5MmE4NDE0YmIiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzIyNjgwNTEwLCJpYXQiOjE3MjI2NzY5MTAsImVtYWlsIjoiZ25hbmlAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6ImduYW5pQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiIzZDQ2MGQ2NC05ODJkLTQ5Y2EtYTFlNS02MzU5MmE4NDE0YmIifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTcyMjY3NjkxMH1dLCJzZXNzaW9uX2lkIjoiOWYyZjNiMjQtNWExNi00ZTlkLWFlNjAtMzE4NjE3MmQxMzAyIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.lUWpdIJTd7RAV6AReGKkU6xuhcydKnaVJBtCoTU-IzE' 

{
    "name": "Gnanendra Gariminti",
    "email": "gnani@gmail.com",
    "password": "123456" 
}

###
POST http://localhost:3000/auth/login 
Content-Type: application/json

{
    "email": "gnani@gmail.com",
    "password": "123456" 
}
###
GET http://localhost:3000/events/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6InZPQVhIN1FWa1FLdXg1V3MiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2N0YWZhb3RvdndqYXp2c2ljbG1zLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI5ODUxZmUyMy1jNjhkLTRhOWYtOTZkZC00M2IwYzliMTFkNzMiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzIyNjgyNjk5LCJpYXQiOjE3MjI2NzkwOTksImVtYWlsIjoiZ25hbmlAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbCI6ImduYW5pQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiI5ODUxZmUyMy1jNjhkLTRhOWYtOTZkZC00M2IwYzliMTFkNzMifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTcyMjY3OTA5OX1dLCJzZXNzaW9uX2lkIjoiNTZjOTQ2MTEtYTMxYy00OTk3LWIxYTYtYjMyYTgyYzczN2E4IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.65kwaVCQv0OjGZtnU55TESL1mOhzt7navpL90KJOrZo